# English translations for PROJECT.
# Copyright (C) 2025 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2025-07-28 23:28+0600\n"
"PO-Revision-Date: 2025-07-28 22:44+0600\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: en\n"
"Language-Team: en <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"

#: helpers.py:165 routes/api/auth.py:241 routes/api/auth.py:248
#, python-format
msgid "Verification code sent to %(target)s"
msgstr ""

#: helpers.py:167 helpers.py:200
#, python-format
msgid "Your code is: %(code)s"
msgstr ""

#: helpers.py:196
msgid "Verification Email"
msgstr ""

#: routes/api/__init__.py:11
msgid "System is under maintenance. Please try again later."
msgstr ""

#: routes/api/auth.py:34 routes/api/auth.py:106
#: routes/api/auth.py:187 routes/api/auth.py:276
#: routes/api/auth.py:483
msgid "Unknown device detected"
msgstr ""

#: routes/api/auth.py:38
msgid "All fields including code are required"
msgstr ""

#: routes/api/auth.py:42 routes/api/auth.py:115
#: routes/api/auth.py:194 routes/api/auth.py:285
msgid "Invalid phone number format"
msgstr ""

#: routes/api/auth.py:79
msgid "Registration successful"
msgstr ""

#: routes/api/auth.py:84 routes/api/auth.py:210
msgid "User with this fullname and phone already registered"
msgstr ""

#: routes/api/auth.py:86 routes/api/auth.py:163
msgid "Internal server error"
msgstr ""

#: routes/api/auth.py:110 routes/api/auth.py:349
#: routes/api/auth.py:431
msgid "All fields are required"
msgstr ""

#: routes/api/auth.py:127 routes/api/auth.py:304
msgid "User not found"
msgstr ""

#: routes/api/auth.py:131
msgid "Incorrect password"
msgstr ""

#: routes/api/auth.py:134 routes/api/auth.py:471
msgid "Account is deactivated"
msgstr ""

#: routes/api/auth.py:151
msgid "Additional info required"
msgstr ""

#: routes/api/auth.py:159
msgid "Login successful"
msgstr ""

#: routes/api/auth.py:190
msgid "Phone number and fullname required"
msgstr ""

#: routes/api/auth.py:227
msgid "Limit reached. Try again later."
msgstr ""

#: routes/api/auth.py:252
msgid "Failed to send verification code"
msgstr ""

#: routes/api/auth.py:256
#, python-format
msgid "Internal error: %(error)s"
msgstr ""

#: routes/api/auth.py:281
msgid "Phone, Fullname, and New Password are required"
msgstr ""

#: routes/api/auth.py:293
msgid "Code successfully matched"
msgstr ""

#: routes/api/auth.py:309
msgid "Incorrect old password"
msgstr ""

#: routes/api/auth.py:314
msgid "New password cannot be the same as the current password."
msgstr ""

#: routes/api/auth.py:322
msgid "Password Reset Successful"
msgstr ""

#: routes/api/auth.py:331
msgid "Invalid page type"
msgstr ""

#: routes/api/auth.py:353 routes/api/payments.py:84
msgid "Invalid phone number"
msgstr ""

#: routes/api/auth.py:368
msgid "Invalid login details"
msgstr ""

#: routes/api/auth.py:372
#, python-format
msgid ""
"Your account has been successfully put for deletion.\n"
"It will take %(days)d days to fully delete your account.\n"
"If it wasn't you, please contact us for account recovery.\n"
"\n"
"@An-Nur.app"
msgstr ""

#: routes/api/auth.py:373
msgid "Account Deletion Confirmation"
msgstr ""

#: routes/api/auth.py:375
msgid ""
"Your account has been successfully deactivated.\n"
"You can reactivate it within our app.\n"
"If it wasn't you, please contact us immediately.\n"
"\n"
"@An-Nur.app"
msgstr ""

#: routes/api/auth.py:376
msgid "Account Deactivation Confirmation"
msgstr ""

#: routes/api/auth.py:392
msgid "Could not send confirmation. Try again later."
msgstr ""

#: routes/api/auth.py:411
msgid "Account deletion initiated. Check your messages."
msgstr ""

#: routes/api/auth.py:414
msgid "Account deactivated successfully."
msgstr ""

#: routes/api/auth.py:418
msgid "An error occurred"
msgstr ""

#: routes/api/auth.py:456
msgid "Account reactivated."
msgstr ""

#: routes/api/auth.py:459
msgid "Account reactivation failed."
msgstr ""

#: routes/api/auth.py:470
msgid "Session invalidated. Please log in again."
msgstr ""

#: routes/api/auth.py:486
msgid "No account information provided."
msgstr ""

#: routes/api/auth.py:609
msgid "Account is valid"
msgstr ""

#: routes/api/auth.py:613
msgid "Internal error"
msgstr ""

#: routes/api/core.py:43
msgid "File not found"
msgstr ""

#: routes/api/core.py:109
msgid "fullname, phone and acc_type are required"
msgstr ""

#: routes/api/core.py:115
msgid "ID not found"
msgstr ""

#: routes/api/core.py:161
msgid "All required fields must be provided for Student"
msgstr ""

#: routes/api/core.py:175 routes/api/core.py:191
#, python-format
msgid "All required fields must be provided for %(type)s"
msgstr ""

#: routes/api/core.py:197
msgid "Name, Phone, and Father/Spouse are required for Guest"
msgstr ""

#: routes/api/core.py:220
#, python-format
msgid "%(type)s profile added successfully"
msgstr ""

#: routes/api/core.py:226
msgid "User already exists with this ID"
msgstr ""

#: routes/api/core.py:229 routes/api/core.py:267
#: routes/api/core.py:300
#, python-format
msgid "Database error: %(error)s"
msgstr ""

#: routes/api/payments.py:40 routes/api/payments.py:305
msgid "User not found for payment"
msgstr ""

#: routes/api/payments.py:44 routes/api/payments.py:319
msgid "Transaction failed"
msgstr ""

#: routes/api/payments.py:78
msgid "Phone, fullname and payment type required"
msgstr ""

#: routes/api/payments.py:111
msgid "Invalid updatedSince format"
msgstr ""

#: routes/api/payments.py:125
msgid "Internal server error during payment processing"
msgstr ""

#: routes/api/payments.py:131
msgid "No transactions found"
msgstr ""

#: routes/api/payments.py:164
msgid "Amount and payment type are required"
msgstr ""

#: routes/api/payments.py:171
msgid "Payment gateway is not properly configured"
msgstr ""

#: routes/api/payments.py:226
msgid "Payment gateway is currently unreachable"
msgstr ""

#: routes/api/payments.py:237
msgid "Payment initiation failed"
msgstr ""

#: routes/api/payments.py:247
msgid "Invalid return type"
msgstr ""

#: routes/api/payments.py:249
msgid "Payment failed"
msgstr ""

#: routes/api/payments.py:251
msgid "Payment cancelled"
msgstr ""

#: routes/api/payments.py:264
msgid "Missing transaction identifier"
msgstr ""

#: routes/api/payments.py:283
msgid "Payment validation failed"
msgstr ""

#: routes/api/payments.py:286
msgid "Error during payment validation"
msgstr ""

#: routes/api/payments.py:324
msgid "Payment recorded successfully"
msgstr ""

